#############################################################################
# Makefile for building: EngineChart
# Generated by qmake (3.1) (Qt 6.7.2)
# Project:  EngineChart.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile EngineChart.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_OPENGLWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -mno-direct-extern-access -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -mno-direct-extern-access -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/qt6 -I/usr/include/qt6/QtCharts -I/usr/include/qt6/QtOpenGLWidgets -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I. -I. -I/usr/lib/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = EngineChart1.0.0
DISTDIR = /home/matteo/Desktop/EngineChart/.tmp/EngineChart1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) /usr/lib/libQt6Charts.so /usr/lib/libQt6OpenGLWidgets.so /usr/lib/libQt6Widgets.so /usr/lib/libQt6OpenGL.so /usr/lib/libQt6Gui.so /usr/lib/libGLX.so /usr/lib/libOpenGL.so /usr/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		src/Container/container.cpp \
		src/DataType/datatype.cpp \
		src/Sensor/abstractsensor.cpp \
		src/Sensor/fuellevel.cpp \
		src/Sensor/humidity.cpp \
		src/Sensor/oilpressure.cpp \
		src/Sensor/speed.cpp \
		src/Sensor/temperature.cpp \
		src/View/additem.cpp \
		src/View/chartdisplaywidget.cpp \
		src/View/edititem.cpp \
		src/View/errorpopup.cpp \
		src/View/infowidget.cpp \
		src/View/inputdialog.cpp \
		src/View/inspectwindow.cpp \
		src/View/mainwindow.cpp \
		src/View/searchaddwidget.cpp \
		src/Visitor/concretevisitor.cpp \
		src/Visitor/sensorvisitor.cpp qrc_Icons.cpp \
		moc_additem.cpp \
		moc_chartdisplaywidget.cpp \
		moc_edititem.cpp \
		moc_errorpopup.cpp \
		moc_infowidget.cpp \
		moc_inputdialog.cpp \
		moc_inspectwindow.cpp \
		moc_mainwindow.cpp \
		moc_searchaddwidget.cpp
OBJECTS       = main.o \
		container.o \
		datatype.o \
		abstractsensor.o \
		fuellevel.o \
		humidity.o \
		oilpressure.o \
		speed.o \
		temperature.o \
		additem.o \
		chartdisplaywidget.o \
		edititem.o \
		errorpopup.o \
		infowidget.o \
		inputdialog.o \
		inspectwindow.o \
		mainwindow.o \
		searchaddwidget.o \
		concretevisitor.o \
		sensorvisitor.o \
		qrc_Icons.o \
		moc_additem.o \
		moc_chartdisplaywidget.o \
		moc_edititem.o \
		moc_errorpopup.o \
		moc_infowidget.o \
		moc_inputdialog.o \
		moc_inspectwindow.o \
		moc_mainwindow.o \
		moc_searchaddwidget.o
DIST          = /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSoapClient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSoapServer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackCore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackWidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroCore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroCoro.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroDBus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroNetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroQml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroQuick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroTest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroWebSockets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_Qt6Keychain.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/uic.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		EngineChart.pro src/Container/container.h \
		src/DataType/datatype.h \
		src/Sensor/abstractsensor.h \
		src/Sensor/fuellevel.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/speed.h \
		src/Sensor/temperature.h \
		src/View/additem.h \
		src/View/chartdisplaywidget.h \
		src/View/edititem.h \
		src/View/errorpopup.h \
		src/View/infowidget.h \
		src/View/inputdialog.h \
		src/View/inspectwindow.h \
		src/View/mainwindow.h \
		src/View/searchaddwidget.h \
		src/Visitor/concretevisitor.h \
		src/Visitor/sensorvisitor.h main.cpp \
		src/Container/container.cpp \
		src/DataType/datatype.cpp \
		src/Sensor/abstractsensor.cpp \
		src/Sensor/fuellevel.cpp \
		src/Sensor/humidity.cpp \
		src/Sensor/oilpressure.cpp \
		src/Sensor/speed.cpp \
		src/Sensor/temperature.cpp \
		src/View/additem.cpp \
		src/View/chartdisplaywidget.cpp \
		src/View/edititem.cpp \
		src/View/errorpopup.cpp \
		src/View/infowidget.cpp \
		src/View/inputdialog.cpp \
		src/View/inspectwindow.cpp \
		src/View/mainwindow.cpp \
		src/View/searchaddwidget.cpp \
		src/Visitor/concretevisitor.cpp \
		src/Visitor/sensorvisitor.cpp
QMAKE_TARGET  = EngineChart
DESTDIR       = 
TARGET        = EngineChart


first: all
####### Build rules

EngineChart: ui_additem.h ui_chartdisplaywidget.h ui_edititem.h ui_errorpopup.h ui_infowidget.h ui_inputdialog.h ui_inspectwindow.h ui_mainwindow.h ui_searchaddwidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EngineChart.pro /usr/lib/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSoapClient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSoapServer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackCore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackWidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroCore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroCoro.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroDBus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroNetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroQml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroQuick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroTest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroWebSockets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_Qt6Keychain.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/uic.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		EngineChart.pro \
		Icons.qrc \
		/usr/lib/libQt6Charts.prl \
		/usr/lib/libQt6OpenGLWidgets.prl \
		/usr/lib/libQt6Widgets.prl \
		/usr/lib/libQt6OpenGL.prl \
		/usr/lib/libQt6Gui.prl \
		/usr/lib/libQt6Core.prl
	$(QMAKE) -o Makefile EngineChart.pro
/usr/lib/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/qt6/mkspecs/common/unix.conf:
/usr/lib/qt6/mkspecs/common/linux.conf:
/usr/lib/qt6/mkspecs/common/sanitize.conf:
/usr/lib/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt6/mkspecs/common/g++-base.conf:
/usr/lib/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/qt6/mkspecs/qconfig.pri:
/usr/lib/qt6/mkspecs/modules/qt_KDSoapClient.pri:
/usr/lib/qt6/mkspecs/modules/qt_KDSoapServer.pri:
/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackCore.pri:
/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackWidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_charts_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlbuiltins.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlbuiltins_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webview.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webview_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroCore.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroCoro.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroDBus.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroNetwork.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroQml.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroQuick.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroTest.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroWebSockets.pri:
/usr/lib/qt6/mkspecs/modules/qt_Qt6Keychain.pri:
/usr/lib/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/qt6/mkspecs/features/qt_config.prf:
/usr/lib/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt6/mkspecs/features/spec_post.prf:
/usr/lib/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt6/mkspecs/features/toolchain.prf:
/usr/lib/qt6/mkspecs/features/default_pre.prf:
/usr/lib/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/qt6/mkspecs/features/default_post.prf:
/usr/lib/qt6/mkspecs/features/warn_on.prf:
/usr/lib/qt6/mkspecs/features/permissions.prf:
/usr/lib/qt6/mkspecs/features/qt.prf:
/usr/lib/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/qt6/mkspecs/features/resources.prf:
/usr/lib/qt6/mkspecs/features/moc.prf:
/usr/lib/qt6/mkspecs/features/link_ltcg.prf:
/usr/lib/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/qt6/mkspecs/features/uic.prf:
/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf:
/usr/lib/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/qt6/mkspecs/features/file_copies.prf:
/usr/lib/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/qt6/mkspecs/features/exceptions.prf:
/usr/lib/qt6/mkspecs/features/yacc.prf:
/usr/lib/qt6/mkspecs/features/lex.prf:
EngineChart.pro:
Icons.qrc:
/usr/lib/libQt6Charts.prl:
/usr/lib/libQt6OpenGLWidgets.prl:
/usr/lib/libQt6Widgets.prl:
/usr/lib/libQt6OpenGL.prl:
/usr/lib/libQt6Gui.prl:
/usr/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile EngineChart.pro

qmake_all: FORCE


all: Makefile EngineChart

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Icons.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/Container/container.h src/DataType/datatype.h src/Sensor/abstractsensor.h src/Sensor/fuellevel.h src/Sensor/humidity.h src/Sensor/oilpressure.h src/Sensor/speed.h src/Sensor/temperature.h src/View/additem.h src/View/chartdisplaywidget.h src/View/edititem.h src/View/errorpopup.h src/View/infowidget.h src/View/inputdialog.h src/View/inspectwindow.h src/View/mainwindow.h src/View/searchaddwidget.h src/Visitor/concretevisitor.h src/Visitor/sensorvisitor.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp src/Container/container.cpp src/DataType/datatype.cpp src/Sensor/abstractsensor.cpp src/Sensor/fuellevel.cpp src/Sensor/humidity.cpp src/Sensor/oilpressure.cpp src/Sensor/speed.cpp src/Sensor/temperature.cpp src/View/additem.cpp src/View/chartdisplaywidget.cpp src/View/edititem.cpp src/View/errorpopup.cpp src/View/infowidget.cpp src/View/inputdialog.cpp src/View/inspectwindow.cpp src/View/mainwindow.cpp src/View/searchaddwidget.cpp src/Visitor/concretevisitor.cpp src/Visitor/sensorvisitor.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/View/additem.ui src/View/chartdisplaywidget.ui src/View/edititem.ui src/View/errorpopup.ui src/View/infowidget.ui src/View/inputdialog.ui src/View/inspectwindow.ui src/View/mainwindow.ui src/View/searchaddwidget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_Icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Icons.cpp
qrc_Icons.cpp: Icons.qrc \
		/usr/lib/qt6/rcc \
		src/Resources/fuel.png \
		src/Resources/appIcon.png \
		src/Resources/temperature.png \
		src/Resources/oilpressure.png \
		src/Resources/speed.png \
		src/Resources/humidity.png
	/usr/lib/qt6/rcc -name Icons Icons.qrc -o qrc_Icons.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_additem.cpp moc_chartdisplaywidget.cpp moc_edititem.cpp moc_errorpopup.cpp moc_infowidget.cpp moc_inputdialog.cpp moc_inspectwindow.cpp moc_mainwindow.cpp moc_searchaddwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_additem.cpp moc_chartdisplaywidget.cpp moc_edititem.cpp moc_errorpopup.cpp moc_infowidget.cpp moc_inputdialog.cpp moc_inspectwindow.cpp moc_mainwindow.cpp moc_searchaddwidget.cpp
moc_additem.cpp: src/View/additem.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/DataType/datatype.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/matteo/Desktop/EngineChart/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/matteo/Desktop/EngineChart -I/home/matteo/Desktop/EngineChart -I/usr/include/qt6 -I/usr/include/qt6/QtCharts -I/usr/include/qt6/QtOpenGLWidgets -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/14.1.1 -I/usr/include/c++/14.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/14.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed -I/usr/include src/View/additem.h -o moc_additem.cpp

moc_chartdisplaywidget.cpp: src/View/chartdisplaywidget.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/DataType/datatype.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/matteo/Desktop/EngineChart/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/matteo/Desktop/EngineChart -I/home/matteo/Desktop/EngineChart -I/usr/include/qt6 -I/usr/include/qt6/QtCharts -I/usr/include/qt6/QtOpenGLWidgets -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/14.1.1 -I/usr/include/c++/14.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/14.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed -I/usr/include src/View/chartdisplaywidget.h -o moc_chartdisplaywidget.cpp

moc_edititem.cpp: src/View/edititem.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/DataType/datatype.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/matteo/Desktop/EngineChart/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/matteo/Desktop/EngineChart -I/home/matteo/Desktop/EngineChart -I/usr/include/qt6 -I/usr/include/qt6/QtCharts -I/usr/include/qt6/QtOpenGLWidgets -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/14.1.1 -I/usr/include/c++/14.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/14.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed -I/usr/include src/View/edititem.h -o moc_edititem.cpp

moc_errorpopup.cpp: src/View/errorpopup.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/matteo/Desktop/EngineChart/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/matteo/Desktop/EngineChart -I/home/matteo/Desktop/EngineChart -I/usr/include/qt6 -I/usr/include/qt6/QtCharts -I/usr/include/qt6/QtOpenGLWidgets -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/14.1.1 -I/usr/include/c++/14.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/14.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed -I/usr/include src/View/errorpopup.h -o moc_errorpopup.cpp

moc_infowidget.cpp: src/View/infowidget.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/matteo/Desktop/EngineChart/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/matteo/Desktop/EngineChart -I/home/matteo/Desktop/EngineChart -I/usr/include/qt6 -I/usr/include/qt6/QtCharts -I/usr/include/qt6/QtOpenGLWidgets -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/14.1.1 -I/usr/include/c++/14.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/14.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed -I/usr/include src/View/infowidget.h -o moc_infowidget.cpp

moc_inputdialog.cpp: src/View/inputdialog.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/matteo/Desktop/EngineChart/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/matteo/Desktop/EngineChart -I/home/matteo/Desktop/EngineChart -I/usr/include/qt6 -I/usr/include/qt6/QtCharts -I/usr/include/qt6/QtOpenGLWidgets -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/14.1.1 -I/usr/include/c++/14.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/14.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed -I/usr/include src/View/inputdialog.h -o moc_inputdialog.cpp

moc_inspectwindow.cpp: src/View/inspectwindow.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/DataType/datatype.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/matteo/Desktop/EngineChart/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/matteo/Desktop/EngineChart -I/home/matteo/Desktop/EngineChart -I/usr/include/qt6 -I/usr/include/qt6/QtCharts -I/usr/include/qt6/QtOpenGLWidgets -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/14.1.1 -I/usr/include/c++/14.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/14.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed -I/usr/include src/View/inspectwindow.h -o moc_inspectwindow.cpp

moc_mainwindow.cpp: src/View/mainwindow.h \
		src/Container/container.h \
		src/View/additem.h \
		src/Sensor/abstractsensor.h \
		src/DataType/datatype.h \
		src/View/chartdisplaywidget.h \
		src/View/infowidget.h \
		src/View/inputdialog.h \
		src/View/inspectwindow.h \
		src/View/searchaddwidget.h \
		src/Visitor/sensorvisitor.h \
		src/Sensor/fuellevel.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/speed.h \
		src/Sensor/temperature.h \
		src/View/edititem.h \
		src/Visitor/concretevisitor.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/matteo/Desktop/EngineChart/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/matteo/Desktop/EngineChart -I/home/matteo/Desktop/EngineChart -I/usr/include/qt6 -I/usr/include/qt6/QtCharts -I/usr/include/qt6/QtOpenGLWidgets -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/14.1.1 -I/usr/include/c++/14.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/14.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed -I/usr/include src/View/mainwindow.h -o moc_mainwindow.cpp

moc_searchaddwidget.cpp: src/View/searchaddwidget.h \
		src/Container/container.h \
		src/Visitor/sensorvisitor.h \
		src/Sensor/fuellevel.h \
		src/DataType/datatype.h \
		src/Sensor/abstractsensor.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/speed.h \
		src/Sensor/temperature.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/matteo/Desktop/EngineChart/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/matteo/Desktop/EngineChart -I/home/matteo/Desktop/EngineChart -I/usr/include/qt6 -I/usr/include/qt6/QtCharts -I/usr/include/qt6/QtOpenGLWidgets -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/14.1.1 -I/usr/include/c++/14.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/14.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed -I/usr/include src/View/searchaddwidget.h -o moc_searchaddwidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_additem.h ui_chartdisplaywidget.h ui_edititem.h ui_errorpopup.h ui_infowidget.h ui_inputdialog.h ui_inspectwindow.h ui_mainwindow.h ui_searchaddwidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_additem.h ui_chartdisplaywidget.h ui_edititem.h ui_errorpopup.h ui_infowidget.h ui_inputdialog.h ui_inspectwindow.h ui_mainwindow.h ui_searchaddwidget.h
ui_additem.h: src/View/additem.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic src/View/additem.ui -o ui_additem.h

ui_chartdisplaywidget.h: src/View/chartdisplaywidget.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic src/View/chartdisplaywidget.ui -o ui_chartdisplaywidget.h

ui_edititem.h: src/View/edititem.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic src/View/edititem.ui -o ui_edititem.h

ui_errorpopup.h: src/View/errorpopup.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic src/View/errorpopup.ui -o ui_errorpopup.h

ui_infowidget.h: src/View/infowidget.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic src/View/infowidget.ui -o ui_infowidget.h

ui_inputdialog.h: src/View/inputdialog.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic src/View/inputdialog.ui -o ui_inputdialog.h

ui_inspectwindow.h: src/View/inspectwindow.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic src/View/inspectwindow.ui -o ui_inspectwindow.h

ui_mainwindow.h: src/View/mainwindow.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic src/View/mainwindow.ui -o ui_mainwindow.h

ui_searchaddwidget.h: src/View/searchaddwidget.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic src/View/searchaddwidget.ui -o ui_searchaddwidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp src/View/mainwindow.h \
		src/Container/container.h \
		src/View/additem.h \
		src/Sensor/abstractsensor.h \
		src/DataType/datatype.h \
		src/View/chartdisplaywidget.h \
		src/View/infowidget.h \
		src/View/inputdialog.h \
		src/View/inspectwindow.h \
		src/View/searchaddwidget.h \
		src/Visitor/sensorvisitor.h \
		src/Sensor/fuellevel.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/speed.h \
		src/Sensor/temperature.h \
		src/View/edititem.h \
		src/Visitor/concretevisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

container.o: src/Container/container.cpp src/Container/container.h \
		src/Sensor/abstractsensor.h \
		src/DataType/datatype.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o container.o src/Container/container.cpp

datatype.o: src/DataType/datatype.cpp src/DataType/datatype.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datatype.o src/DataType/datatype.cpp

abstractsensor.o: src/Sensor/abstractsensor.cpp src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/DataType/datatype.h \
		src/Sensor/fuellevel.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/temperature.h \
		src/Sensor/speed.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abstractsensor.o src/Sensor/abstractsensor.cpp

fuellevel.o: src/Sensor/fuellevel.cpp src/Sensor/fuellevel.h \
		src/DataType/datatype.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/Visitor/sensorvisitor.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/speed.h \
		src/Sensor/temperature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fuellevel.o src/Sensor/fuellevel.cpp

humidity.o: src/Sensor/humidity.cpp src/Sensor/humidity.h \
		src/DataType/datatype.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/Visitor/sensorvisitor.h \
		src/Sensor/fuellevel.h \
		src/Sensor/oilpressure.h \
		src/Sensor/speed.h \
		src/Sensor/temperature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o humidity.o src/Sensor/humidity.cpp

oilpressure.o: src/Sensor/oilpressure.cpp src/Sensor/oilpressure.h \
		src/DataType/datatype.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/Visitor/sensorvisitor.h \
		src/Sensor/fuellevel.h \
		src/Sensor/humidity.h \
		src/Sensor/speed.h \
		src/Sensor/temperature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oilpressure.o src/Sensor/oilpressure.cpp

speed.o: src/Sensor/speed.cpp src/Sensor/speed.h \
		src/DataType/datatype.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/Visitor/sensorvisitor.h \
		src/Sensor/fuellevel.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/temperature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speed.o src/Sensor/speed.cpp

temperature.o: src/Sensor/temperature.cpp src/Sensor/temperature.h \
		src/DataType/datatype.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/Visitor/sensorvisitor.h \
		src/Sensor/fuellevel.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/speed.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temperature.o src/Sensor/temperature.cpp

additem.o: src/View/additem.cpp src/View/additem.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/DataType/datatype.h \
		src/Sensor/fuellevel.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/temperature.h \
		src/Sensor/speed.h \
		src/View/errorpopup.h \
		ui_additem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o additem.o src/View/additem.cpp

chartdisplaywidget.o: src/View/chartdisplaywidget.cpp src/View/chartdisplaywidget.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/DataType/datatype.h \
		src/Visitor/concretevisitor.h \
		src/Visitor/sensorvisitor.h \
		src/Sensor/fuellevel.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/speed.h \
		src/Sensor/temperature.h \
		ui_chartdisplaywidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chartdisplaywidget.o src/View/chartdisplaywidget.cpp

edititem.o: src/View/edititem.cpp src/View/edititem.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/DataType/datatype.h \
		src/View/errorpopup.h \
		ui_edititem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edititem.o src/View/edititem.cpp

errorpopup.o: src/View/errorpopup.cpp src/View/errorpopup.h \
		ui_errorpopup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errorpopup.o src/View/errorpopup.cpp

infowidget.o: src/View/infowidget.cpp src/View/infowidget.h \
		ui_infowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o infowidget.o src/View/infowidget.cpp

inputdialog.o: src/View/inputdialog.cpp src/View/inputdialog.h \
		ui_inputdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputdialog.o src/View/inputdialog.cpp

inspectwindow.o: src/View/inspectwindow.cpp src/View/inspectwindow.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/DataType/datatype.h \
		ui_inspectwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inspectwindow.o src/View/inspectwindow.cpp

mainwindow.o: src/View/mainwindow.cpp src/View/mainwindow.h \
		src/Container/container.h \
		src/View/additem.h \
		src/Sensor/abstractsensor.h \
		src/DataType/datatype.h \
		src/View/chartdisplaywidget.h \
		src/View/infowidget.h \
		src/View/inputdialog.h \
		src/View/inspectwindow.h \
		src/View/searchaddwidget.h \
		src/Visitor/sensorvisitor.h \
		src/Sensor/fuellevel.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/speed.h \
		src/Sensor/temperature.h \
		src/View/edititem.h \
		src/Visitor/concretevisitor.h \
		src/View/errorpopup.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/View/mainwindow.cpp

searchaddwidget.o: src/View/searchaddwidget.cpp src/View/searchaddwidget.h \
		src/Container/container.h \
		src/Visitor/sensorvisitor.h \
		src/Sensor/fuellevel.h \
		src/DataType/datatype.h \
		src/Sensor/abstractsensor.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/speed.h \
		src/Sensor/temperature.h \
		ui_searchaddwidget.h \
		src/View/mainwindow.h \
		src/View/additem.h \
		src/View/chartdisplaywidget.h \
		src/View/infowidget.h \
		src/View/inputdialog.h \
		src/View/inspectwindow.h \
		src/View/edititem.h \
		src/Visitor/concretevisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchaddwidget.o src/View/searchaddwidget.cpp

concretevisitor.o: src/Visitor/concretevisitor.cpp src/Visitor/concretevisitor.h \
		src/Visitor/sensorvisitor.h \
		src/Sensor/fuellevel.h \
		src/DataType/datatype.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/speed.h \
		src/Sensor/temperature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o concretevisitor.o src/Visitor/concretevisitor.cpp

sensorvisitor.o: src/Visitor/sensorvisitor.cpp src/Visitor/sensorvisitor.h \
		src/Sensor/fuellevel.h \
		src/DataType/datatype.h \
		src/Sensor/abstractsensor.h \
		src/Container/container.h \
		src/Sensor/humidity.h \
		src/Sensor/oilpressure.h \
		src/Sensor/speed.h \
		src/Sensor/temperature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sensorvisitor.o src/Visitor/sensorvisitor.cpp

qrc_Icons.o: qrc_Icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Icons.o qrc_Icons.cpp

moc_additem.o: moc_additem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_additem.o moc_additem.cpp

moc_chartdisplaywidget.o: moc_chartdisplaywidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chartdisplaywidget.o moc_chartdisplaywidget.cpp

moc_edititem.o: moc_edititem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_edititem.o moc_edititem.cpp

moc_errorpopup.o: moc_errorpopup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_errorpopup.o moc_errorpopup.cpp

moc_infowidget.o: moc_infowidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_infowidget.o moc_infowidget.cpp

moc_inputdialog.o: moc_inputdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inputdialog.o moc_inputdialog.cpp

moc_inspectwindow.o: moc_inspectwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inspectwindow.o moc_inspectwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_searchaddwidget.o: moc_searchaddwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_searchaddwidget.o moc_searchaddwidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

